### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by polm** [wustho/epr#35]
Out of curiosity, any reason this isn't on PyPI? I saw #11 but it didn't mention any particular reason.

**Comment by wustho** [comment]
Hello there, initially I made this script to learn python, so at that time I dont know much about pypi packaging, and since pip+git already does easy installation method, I don't bother reading pypi packaging...

But because now this hits 500 stars, I think I will make next version available from pypi...

**Comment by polm** [comment]
Sounds great! If I can help with anything let me know.

**Comment by wustho** [comment]
Of course there's so much helps and ideas needed and are welcome :) ... But sorry if the code isn't commented and described properly, because I don't have degree in any programming related degree, I even forgot some variables that I made myself... I'll try to make it easier to other people to read them...

**Comment by wustho** [comment]
https://pypi.org/project/epr-reader/ <-- now on pypi
