### ISSUE TITLE
Improvement: reset zoom with zero key

### ISSUE THREAD

**Issue by sandersantema** [wustho/epr#9]
Usually when a zoom functionality is offered apps zoom in/out with ```+``` (or ```=```) and ```-``` respectively. Most of the time they also offer a way to reset the zoom level back to normal. I think that would be a good addition to epr to.

**Comment by wustho** [comment]
Hey there Sandersantema, that's good feedback, thanks.

But I think it's better to wait dsanson from issue #5 for him to implement vim like prefix key, so when we press `6j` we get cursor moved down six times. As for default text area width, I hope we can get it by prefixing `0` to `=`, furthermore we can get 120 columns text area width by simply `120=` rather than holding `=`. Although we're probably not in hurry.

**Comment by wustho** [comment]
Hello there, looks like reset key is pretty useful, I just add it with 0 (zero) key in recent commit, sorry took a while
